---
version: "2.0"
services:
  texttoimage:
    image: cro7/flux-schnell-on-akash:0.0.1
    expose:
      - port: 7860
        as: 7860
        to:
          - global: true
profiles:
  compute:
    texttoimage:
      resources:
        cpu:
          units: 6
        memory:
          size: 32Gi
        storage:
          - size: 40Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
  placement:
    dcloud:
      pricing:
        texttoimage:
          denom: uakt
          amount: 1000
deployment:
  texttoimage:
    dcloud:
      profile: texttoimage
      count: 1